"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
type Account={id:string;accountNumber:string;type:string;currency:string;status:string};
export default function TransferPage(){
 const [accounts,setAccounts]=useState<Account[]>([]),[fromAccountId,setFrom]=useState(""),[toAccountNumber,setTo]=useState(""),[amount,setAmount]=useState(""),[description,setDescription]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/accounts").then(async r=>{if(r.ok)setAccounts((await r.json()).accounts);else if(r.status===401)window.location.href="/login"})},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/transfers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fromAccountId,toAccountNumber,amount,description})});const data=await r.json();if(!r.ok){setMessage(data.error||"Transfer failed.");return}setMessage(`Transfer ${data.transaction.reference} completed successfully.`);setAmount("");setDescription("");setTo("")}finally{setBusy(false)}}
 return <main className="min-h-screen bg-trust-50"><div className="container max-w-2xl py-10"><Link href="/dashboard" className="text-sm font-semibold text-trust-700">← Dashboard</Link><div className="mt-5 rounded-3xl border border-trust-100 bg-white p-7 shadow-soft"><h1 className="text-3xl font-bold">Send money</h1><p className="mt-2 text-slate-500">Transfer funds securely to another SolidTrust account.</p><form onSubmit={submit} className="mt-8 space-y-5"><label className="block"><span className="text-sm font-semibold">From account</span><select required value={fromAccountId} onChange={e=>setFrom(e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="">Select account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.type} · {a.accountNumber}</option>)}</select></label><label className="block"><span className="text-sm font-semibold">Recipient account number</span><input required value={toAccountNumber} onChange={e=>setTo(e.target.value)} className="mt-2 w-full rounded-xl border p-3" placeholder="30XXXXXXXX"/></label><label className="block"><span className="text-sm font-semibold">Amount</span><input required min="0.01" step="0.01" type="number" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-2 w-full rounded-xl border p-3" placeholder="0.00"/></label><label className="block"><span className="text-sm font-semibold">Description <span className="font-normal text-slate-400">(optional)</span></span><input value={description} onChange={e=>setDescription(e.target.value)} className="mt-2 w-full rounded-xl border p-3" placeholder="What is this transfer for?"/></label>{message&&<p className="rounded-xl bg-trust-50 p-3 text-sm text-trust-800">{message}</p>}<button disabled={busy} className="w-full rounded-xl bg-trust-700 px-5 py-3 font-semibold text-white disabled:opacity-50">{busy?"Sending…":"Send money"}</button></form></div></div></main>
}
